// server/src/lib/pricing.goldenMaster.test.js
//
// GOLDEN-MASTER (characterization) drift guard for the canonical pricing
// formulas in shared/pricingMath.js and the server verification path in
// pricingVerifier.js.
//
// ⚠️  These pinned values are a CHARACTERIZATION SNAPSHOT of the CURRENT shared
//     implementation's behaviour — they are NOT actuarially approved. Their job
//     is to make ANY change to the canonical math (or to the server verifier's
//     re-derivation) fail CI, so server and client can never silently diverge.
//     Replace these literals with an actuary-signed-off example set when one is
//     provided (see docs/pricing-signoff-required.md). Do NOT "fix" a failure by
//     editing the expected numbers without understanding why the math moved.
//
// The literals were generated by running the current shared formulas over the
// inputs below; they are frozen here (not recomputed at test time) so the test
// genuinely pins behaviour rather than tautologically re-deriving it.

import { describe, it, expect } from 'vitest';
import {
  deriveComponentTotal, applyLoading, layerHit, parseLooseNumber,
  weightedAverage, rolFromAnnualLoss, premiumFromRol,
} from '../../../shared/pricingMath.js';
import { verifyNpPricingOutputs } from './pricingVerifier.js';

// args: [pureBurn, pareto, exposure, wBurn, wPareto, wExp, loading]
const GOLDEN_COMPONENT = [
  { name: 'plain numbers',        args: [0.10, 0.12, 0.08, 40, 30, 30, 20],             expected: 0.125 },
  { name: 'formatted strings',    args: ['8.00%', '0.12', '0.08', '40', '30', '30', '20'], expected: 4.075 },
  { name: 'no loading',           args: [0.10, 0.10, 0.10, 33.34, 33.33, 33.33, 0],     expected: 0.1 },
  { name: 'burn only',            args: [0.15, 0, 0, 100, 0, 0, 10],                    expected: 0.1666666667 },
  { name: 'high loading',         args: [0.05, 0.05, 0.05, 50, 25, 25, 50],             expected: 0.1 },
  { name: 'zero weight → 0',      args: [0.10, 0.20, 0.30, 0, 0, 0, 0],                 expected: 0 },
];

const GOLDEN_PRIMITIVES = [
  { name: 'applyLoading(0.10, 20)',          fn: () => applyLoading(0.10, 20),               expected: 0.125 },
  { name: 'layerHit(1000, 200, 500)',        fn: () => layerHit(1000, 200, 500),             expected: 500 },
  { name: 'parseLooseNumber("$2,000")',      fn: () => parseLooseNumber('$2,000'),           expected: 2000 },
  { name: 'parseLooseNumber("8.00%")',       fn: () => parseLooseNumber('8.00%'),            expected: 8 },
  { name: 'weightedAverage',                 fn: () => weightedAverage([0.1, 0.2, 0.3], [40, 30, 30]), expected: 0.19 },
  { name: 'rolFromAnnualLoss(50, 1000)',     fn: () => rolFromAnnualLoss(50, 1000),          expected: 0.05 },
  { name: 'premiumFromRol(0.05, 1000)',      fn: () => premiumFromRol(0.05, 1000),           expected: 50 },
];

// Build a verifier output row from a golden component entry, pinning total_price
// to the snapshot value so the server re-derivation must agree (no drift).
function rowFromGolden(g, i, totalOverride) {
  const [pure, pareto, exposure, wB, wP, wE, loading] = g.args;
  return {
    layer_number: i + 1,
    section: 'GOLDEN',
    pure_burning_cost: pure,
    pareto_pricing: pareto,
    exposure_rating: exposure,
    burn_weight_pct: wB,
    pareto_weight_pct: wP,
    exposure_weight_pct: wE,
    pricing_loading_pct: loading,
    total_price: totalOverride ?? g.expected,
  };
}

describe('pricing golden master (characterization snapshot — NOT actuarially approved)', () => {
  it('deriveComponentTotal matches the pinned snapshot for every case', () => {
    for (const g of GOLDEN_COMPONENT) {
      expect(deriveComponentTotal(...g.args), g.name).toBeCloseTo(g.expected, 9);
    }
  });

  it('core shared primitives match the pinned snapshot', () => {
    for (const p of GOLDEN_PRIMITIVES) {
      expect(p.fn(), p.name).toBeCloseTo(p.expected, 9);
    }
  });

  it('server verifier re-derives the snapshot identically — no drift on pinned rows', () => {
    // Only the weight-summing-to-100 rows (excludes the zero-weight edge case,
    // which legitimately flags a weights_sum drift).
    const rows = GOLDEN_COMPONENT
      .filter((g) => g.args[3] + g.args[4] + g.args[5] > 0)
      .map((g, i) => rowFromGolden(g, i));
    expect(verifyNpPricingOutputs(rows)).toEqual([]);
  });

  it('server verifier parses formatted strings the same way the formula does', () => {
    // The "formatted strings" entry stores "8.00%"/"0.12"/... and a pinned total;
    // the verifier must re-derive the identical total (the resolved parser-parity
    // finding) rather than zeroing the strings → phantom drift.
    const formatted = GOLDEN_COMPONENT.find((g) => g.name === 'formatted strings');
    expect(verifyNpPricingOutputs([rowFromGolden(formatted, 0)])).toEqual([]);
  });

  it('server verifier REJECTS drift (a tampered total fails the spot check) — this is the CI guard', () => {
    const g = GOLDEN_COMPONENT[0];
    const drifts = verifyNpPricingOutputs([rowFromGolden(g, 0, g.expected * 1.1)]);
    expect(drifts.length).toBeGreaterThan(0);
    expect(drifts.some((d) => d.field === 'total_price')).toBe(true);
  });
});
