// goldenMaster.test.jsx — Phase 4.2 safety net for the NpStopLossPricing
// decomposition (docs/frontend-hardening.md).
//
// Pins the EXACT observable output of the stop-loss pricing money path as
// literal values captured from the pre-refactor screen:
//   • on-level burning-cost table (adjusted premium × factor, loss ratios,
//     per-layer layer hits) driven by an EGNPI fixture with a rate-change
//     chain whose on-level factors are ≠ 1,
//   • the resolved layer line (limit xs attach in currency),
//   • the per-method result cards (burning cost, exposure rating, and a
//     seeded Monte Carlo run pinned in its own test),
//   • the blended result rows + multi-layer TOTAL row,
//   • the full saveNpStopLossPricing payload (inputs + outputs snapshot,
//     incl. per-layer blended numbers) fired on wizard save,
//   • the npStopLossInputs slice contract: the setSlice write on edit, the
//     replaceSlice merge-under-current on hydration, and the legacy-shape
//     (top-level attachment/limit/epi) → layers[] migration.
//
// Every literal below was generated by running the real engine
// (client/src/logic/stopLossPricing.js + shared/onLevel.js) against this
// fixture and verified against the pre-refactor screen across 3 runs.
// Monte Carlo is OFF in the main fixture; the MC test relies on the seeded
// mulberry32 PRNG being bit-identical for a fixed seed.
//
// RULE: these expectations may NEVER be edited as part of a refactor. If a
// refactor makes one of these assertions fail, the refactor changed pricing
// behaviour — fix the refactor, not the test.
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';

// The screen imports the api module's DEFAULT export (`import api from
// '../../../api'`); the named alias is provided too so extracted hooks may
// use either style without changing behaviour.
const apiMock = vi.hoisted(() => ({
  getNpStopLossPricing: vi.fn(),
  saveNpStopLossPricing: vi.fn(),
  getNpEgnpiYear: vi.fn(),
}));
vi.mock('../../../api', () => ({ __esModule: true, default: apiMock, api: apiMock }));
vi.mock('../../../hooks/useContractId', () => ({
  __esModule: true,
  useContractId: () => 'SL-GM-1',
  default: () => 'SL-GM-1',
}));
vi.mock('../../../components/WizardLayout', () => ({
  __esModule: true,
  default: function FakeWizardLayout({ children, onBeforeNext }) {
    return (
      <div>
        <button type="button" onClick={() => onBeforeNext && onBeforeNext()}>go to next step</button>
        {typeof children === 'function' ? children() : children}
      </div>
    );
  },
}));

// Static AppContext mock: state is fixed per test; setSlice / replaceSlice
// are spies so every slice write the screen performs is pinned by argument.
const ctx = vi.hoisted(() => ({ state: {}, setSlice: null, replaceSlice: null }));
vi.mock('../../../context/AppContext', () => ({
  useAppState: () => ({ state: ctx.state, setSlice: ctx.setSlice, replaceSlice: ctx.replaceSlice }),
}));

import NpStopLossPricing from './NpStopLossPricing.jsx';

// ── Fixture ─────────────────────────────────────────────────────────────────
// UW year 2025, experience from 2020 → years 2020..2024. Rate-change chain:
// +5% (2021), −2% (2022), +4% (2023), +3% (2024) → on-level factors
// 1.102 / 1.050 / 1.071 / 1.030 / 1.000.
const EGNPI_ROWS = [
  { uw_year: 2020, egnpi: '8000000', rate_change_pct: null },
  { uw_year: 2021, egnpi: '8500000', rate_change_pct: '5' },
  { uw_year: 2022, egnpi: '9000000', rate_change_pct: '-2' },
  { uw_year: 2023, egnpi: '9500000', rate_change_pct: '4' },
  { uw_year: 2024, egnpi: '10000000', rate_change_pct: '3' },
];

const TREATY_DETAIL = {
  startYear: '2025',
  experienceStartYear: '2020',
  numberOfLayers: 2,
  treatyTypeName: 'Stop Loss',
};

// 2 layers: 20% xs 80% LR and 25% xs 100% LR, both on EPI 10,000,000.
// Burning cost AND exposure rating both compute; loading 25% > 0; MC off.
const SLICE = {
  layers: [
    { attachmentLossRatio: '80', limitLossRatio: '20', epi: '10000000' },
    { attachmentLossRatio: '100', limitLossRatio: '25', epi: '10000000' },
  ],
  yearlyAggregates: [
    { year: 2020, aggregate: '9200000' },
    { year: 2021, aggregate: '7000000' },
    { year: 2022, aggregate: '9800000' },
    { year: 2023, aggregate: '11500000' },
    { year: 2024, aggregate: '8200000' },
  ],
  freqLambda: '25',
  severityType: 'lognormal',
  sevMean: '300000',
  sevCv: '0.8',
  weightBurningCost: '60',
  weightExposureRating: '40',
  weightMonteCarlo: '0',
  loading: '25',
  useMonteCarlo: false,
  mcTrials: '10000',
  mcSeed: '1',
};

function setAppState({ slice = SLICE, detail = TREATY_DETAIL } = {}) {
  ctx.state = {
    quoteMode: false,
    npTreatyDetail: detail,
    ...(slice === undefined ? {} : { npStopLossInputs: slice }),
  };
}

// Serialize a table into a cell matrix. Inputs render as "[value]", static
// cells as trimmed textContent — the literals pin both the value AND whether
// the cell is an editable input.
const rowsOf = (table) => Array.from(table.querySelectorAll('tr')).map((tr) =>
  Array.from(tr.querySelectorAll('th,td')).map((cell) => {
    const input = cell.querySelector('input');
    if (input) return input.type === 'checkbox' ? `[${input.checked ? 'x' : ' '}]` : `[${input.value}]`;
    return (cell.textContent || '').trim();
  }));

const sectionOf = (title) => screen.getByText(title).parentElement;
const tableOf = (title) => sectionOf(title).querySelector('table');
// Direct child <div>s of a section: [title, sub, table-or-form, …summaries].
const gridsOf = (title) => Array.from(sectionOf(title).children).filter((el) => el.tagName === 'DIV');

const BURNING_COST_MATRIX = [
  ['UW Year', 'Premium (Adjusted)', 'Aggregate Loss', 'Loss Ratio', 'L1 Hit', 'L2 Hit'],
  ['2020', '8,818,118×1.102', '[9,200,000]', '104.3%', '2,000,000', '433,065'],
  ['2021', '8,923,096×1.050', '[7,000,000]', '78.4%', '—', '—'],
  ['2022', '9,640,800×1.071', '[9,800,000]', '101.7%', '2,000,000', '165,132'],
  ['2023', '9,785,000×1.030', '[11,500,000]', '117.5%', '2,000,000', '1,752,683'],
  ['2024', '10,000,000', '[8,200,000]', '82.0%', '200,000', '—'],
];

const settle = async () => {
  // EGNPI fixture hydrated → on-level premiums and LRs computed.
  await waitFor(() => expect(rowsOf(tableOf('Burning Cost · Loss Ratios by UW Year'))).toEqual(BURNING_COST_MATRIX));
  // Server snapshot hydrated → useScreenSave is loaded (replaceSlice fired).
  await waitFor(() => expect(ctx.replaceSlice).toHaveBeenCalledTimes(1));
};

afterEach(() => { cleanup(); vi.restoreAllMocks(); });
beforeEach(() => {
  apiMock.getNpStopLossPricing.mockReset().mockResolvedValue({ inputs: { mcTrials: '25000' }, outputs: null });
  apiMock.saveNpStopLossPricing.mockReset().mockResolvedValue({ ok: true });
  apiMock.getNpEgnpiYear.mockReset().mockResolvedValue(EGNPI_ROWS);
  ctx.setSlice = vi.fn();
  ctx.replaceSlice = vi.fn();
  setAppState();
});

describe('NpStopLossPricing golden master (MC off — deterministic)', () => {
  it('reproduces every computed cell, card and slice write, and the exact save payload', async () => {
    render(<NpStopLossPricing />);
    await settle();
    expect(apiMock.getNpEgnpiYear).toHaveBeenCalledWith('SL-GM-1', undefined);
    expect(apiMock.getNpStopLossPricing).toHaveBeenCalledWith('SL-GM-1', undefined);

    /* ═══ 1. Layer cover — read-only mirror + resolved currency line ═══ */
    expect(rowsOf(tableOf('Layer Cover · Loss-Ratio Basis'))).toEqual([
      ['Layer', 'Attach LR %', 'Limit LR %', 'EPI', 'Resolved · Limit xs Attach'],
      ['L1', '80%', '20%', '10,000,000', '2,000,000 xs 8,000,000'],
      ['L2', '100%', '25%', '10,000,000', '2,500,000 xs 10,000,000'],
    ]);

    /* ═══ 2. Burning cost summary cards (annual loss / ROL / years) ═══ */
    // (6,200,000 in layer over 5 years → 1,240,000/yr → 62% ROL on 2M.)
    const bcGrids = gridsOf('Burning Cost · Loss Ratios by UW Year');
    expect(bcGrids[3].textContent).toBe(
      'Annual Loss1.24M1,240,000ROL62.000%—Years Observed5incl. zero-loss years',
    );

    /* ═══ 3. Exposure rating cards (compound Poisson, Normal approx) ═══ */
    // λ=25 × lognormal(mean 300k, CV 0.8): E[S]=7.5M, σ[S]=1,920,937.
    const erGrids = gridsOf('Exposure Rating · Compound Poisson');
    expect(erGrids[3].textContent).toBe(
      'Layer Loss455.0K454,970ROL22.749%Loss / 2.00ME[S]7.50M7,500,000σ[S]1.92M1,920,937',
    );

    /* ═══ 4. Blended result by layer (60/40 blend, 25% loading) ═══ */
    expect(rowsOf(tableOf('Blended Result · By Layer'))).toEqual([
      ['Layer', 'Limit xs Attach', 'Annual Layer Loss', 'Pure ROL', 'Total Rate', 'Premium'],
      ['L1', '2,000,000 xs 8,000,000', '925,988', '46.299%', '61.733%', '1,234,651'],
      ['L2', '2,500,000 xs 10,000,000', '315,866', '12.635%', '16.846%', '421,155'],
      ['TOTAL', '4,500,000', '1,241,854', '27.597%', '—', '1,655,805'],
    ]);
    expect(screen.queryByText('Warnings')).toBeNull();

    /* ═══ 5. Hydration slice contract: merge-under-current ═══ */
    // Server snapshot only carried mcTrials='25000'; every populated
    // AppContext field (incl. the slice's own mcTrials='10000') wins, and
    // DEFAULT_INPUTS fill the rest — pinned as the exact replaceSlice arg.
    const HYDRATED_INPUTS = {
      layers: SLICE.layers,
      yearlyAggregates: SLICE.yearlyAggregates,
      freqLambda: '25',
      severityType: 'lognormal',
      sevMean: '300000',
      sevCv: '0.8',
      paretoAlpha: '',
      paretoTheta: '',
      weightBurningCost: '60',
      weightExposureRating: '40',
      weightMonteCarlo: '0',
      loading: '25',
      useMonteCarlo: false,
      mcTrials: '10000',
      mcSeed: '1',
    };
    expect(ctx.replaceSlice).toHaveBeenCalledWith('npStopLossInputs', HYDRATED_INPUTS);

    /* ═══ 6. Edit slice contract: setSlice carries the full year column ═══ */
    const row2020 = screen.getByText('2020').closest('tr');
    fireEvent.change(row2020.querySelector('input'), { target: { value: '9999999' } });
    expect(ctx.setSlice).toHaveBeenCalledTimes(1);
    expect(ctx.setSlice).toHaveBeenCalledWith('npStopLossInputs', {
      yearlyAggregates: [
        { year: 2020, aggregate: '9999999' },
        { year: 2021, aggregate: '7000000' },
        { year: 2022, aggregate: '9800000' },
        { year: 2023, aggregate: '11500000' },
        { year: 2024, aggregate: '8200000' },
      ],
    });

    /* ═══ 7. Wizard save: full inputs + outputs snapshot payload ═══ */
    // (The mocked context is static, so the screen still prices the
    // original fixture — the edit above only marked the screen dirty.)
    fireEvent.click(screen.getByRole('button', { name: /go to next step/i }));
    await waitFor(() => expect(apiMock.saveNpStopLossPricing).toHaveBeenCalledTimes(1));
    const [savedId, payload, savedOpts] = apiMock.saveNpStopLossPricing.mock.calls[0];
    expect(savedId).toBe('SL-GM-1');
    expect(savedOpts).toBeUndefined();
    expect(payload).toEqual({
      inputs: HYDRATED_INPUTS,
      outputs: {
        attachment: 8000000,
        limit: 2000000,
        blended: {
          annualLoss: 925988.1348898947,
          rol: 0.46299406744494737,
          totalRate: 0.6173254232599298,
        },
        burningCost: {
          annualLoss: 1239999.9999999998,
          rol: 0.6199999999999999,
          nYears: 5,
        },
        exposureRating: {
          annualLoss: 454970.33722473704,
          rol: 0.22748516861236853,
          aggMean: 7499999.999999997,
          aggStd: 1920937.2712298564,
          normalApproxValid: true,
        },
        monteCarlo: null,
        warnings: [],
        layers: [
          {
            layer: 1,
            attachment: 8000000,
            limit: 2000000,
            blended: {
              annualLoss: 925988.1348898947,
              rol: 0.46299406744494737,
              totalRate: 0.6173254232599298,
            },
            burningCostRol: 0.6199999999999999,
            exposureRol: 0.22748516861236853,
            monteCarloRol: null,
          },
          {
            layer: 2,
            attachment: 10000000,
            limit: 2500000,
            blended: {
              annualLoss: 315865.9713747853,
              rol: 0.12634638854991412,
              totalRate: 0.16846185139988548,
            },
            burningCostRol: 0.18807031397314294,
            exposureRol: 0.03376050041507084,
            monteCarloRol: null,
          },
        ],
      },
    });
  });
});

describe('NpStopLossPricing golden master (seeded Monte Carlo)', () => {
  it('reproduces the exact MC cards, percentiles and blended rows for seed 42', async () => {
    setAppState({
      slice: { ...SLICE, useMonteCarlo: true, weightMonteCarlo: '20', mcTrials: '5000', mcSeed: '42' },
    });
    render(<NpStopLossPricing />);
    await settle();

    // mulberry32(42) × 5,000 trials — bit-identical on every run.
    const mcGrids = gridsOf('Monte Carlo · Aggregate Simulation');
    expect(mcGrids[3].textContent).toBe(
      'Layer Loss431.3K431,313ROL21.566%Loss / 2.00MCV1.64σ / meanHit Frequency36.9%Pr(layer hit > 0)',
    );
    expect(mcGrids[4].textContent).toBe(
      'P500P75691,283P902,000,000P952,000,000P992,000,000',
    );

    // Three-way blend 60/40/20 (normalised by Σ=120), 25% loading.
    expect(rowsOf(tableOf('Blended Result · By Layer'))).toEqual([
      ['Layer', 'Limit xs Attach', 'Annual Layer Loss', 'Pure ROL', 'Total Rate', 'Premium'],
      ['L1', '2,000,000 xs 8,000,000', '843,542', '42.177%', '56.236%', '1,124,723'],
      ['L2', '2,500,000 xs 10,000,000', '281,423', '11.257%', '15.009%', '375,231'],
      ['TOTAL', '4,500,000', '1,124,966', '24.999%', '—', '1,499,954'],
    ]);
  });
});

describe('NpStopLossPricing golden master (hydration slice contract)', () => {
  it('migrates a legacy flat snapshot to layers[] and keeps Structure-page fields on top', async () => {
    // Records saved before the layers refactor: layer 0 lived as top-level
    // attachmentLossRatio / limitLossRatio / epi. The Structure page has
    // since written a fresher layers[] into the slice — it must win, while
    // the engine-only server fields hydrate in underneath.
    apiMock.getNpStopLossPricing.mockResolvedValue({
      inputs: {
        attachmentLossRatio: '70',
        limitLossRatio: '30',
        epi: '5000000',
        loading: '30',
        freqLambda: '12',
        sevMean: '250000',
        sevCv: '0.7',
      },
      outputs: null,
    });
    setAppState({
      slice: { layers: [{ attachmentLossRatio: '85', limitLossRatio: '15', epi: '12000000' }] },
    });
    render(<NpStopLossPricing />);

    await waitFor(() => expect(ctx.replaceSlice).toHaveBeenCalledTimes(1));
    expect(ctx.replaceSlice).toHaveBeenCalledWith('npStopLossInputs', {
      // current (Structure-page) layers beat the migrated legacy layer…
      layers: [{ attachmentLossRatio: '85', limitLossRatio: '15', epi: '12000000' }],
      // …the legacy top-level fields ride along unchanged…
      attachmentLossRatio: '70',
      limitLossRatio: '30',
      epi: '5000000',
      // …server engine fields hydrate in, defaults fill the rest.
      yearlyAggregates: [],
      freqLambda: '12',
      severityType: 'lognormal',
      sevMean: '250000',
      sevCv: '0.7',
      paretoAlpha: '',
      paretoTheta: '',
      weightBurningCost: '50',
      weightExposureRating: '50',
      weightMonteCarlo: '0',
      loading: '30',
      useMonteCarlo: false,
      mcTrials: '10000',
      mcSeed: '1',
    });
  });

  it('leaves the slice untouched when the server has no saved inputs', async () => {
    apiMock.getNpStopLossPricing.mockResolvedValue({ inputs: {}, outputs: null });
    render(<NpStopLossPricing />);
    await waitFor(() => expect(apiMock.getNpStopLossPricing).toHaveBeenCalledTimes(1));
    await waitFor(() => expect(rowsOf(tableOf('Burning Cost · Loss Ratios by UW Year'))).toEqual(BURNING_COST_MATRIX));
    expect(ctx.replaceSlice).not.toHaveBeenCalled();
  });
});
