// Snapshot tests for the renewal-pack parser.
//
// Fixtures live at <repo>/test/fixtures/renewal-packs/ and are generated by
// server/scripts/generate-renewal-pack-fixtures.js. Snapshots are committed
// so a behavioural drift in the parser surfaces as a test failure rather
// than a silent change in production output.

import { describe, it, expect } from 'vitest';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import ExcelJS from 'exceljs';
import { parseRenewalPack } from './parser.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// vitest runs from server/, so fixtures are two levels up.
const FIXTURES_DIR = path.resolve(__dirname, '../../../../test/fixtures/renewal-packs');

const PROP_FILES = Array.from({ length: 10 }, (_, i) => `PROP_${String(i + 1).padStart(2, '0')}.xlsx`);
const NP_FILES = Array.from({ length: 10 }, (_, i) => `NP_${String(i + 1).padStart(2, '0')}.xlsx`);

describe('parseRenewalPack', () => {
  it('locates the fixtures directory', () => {
    expect(fs.existsSync(FIXTURES_DIR)).toBe(true);
  });

  describe.each(PROP_FILES)('%s', (file) => {
    it('parses and matches snapshot', async () => {
      const buf = fs.readFileSync(path.join(FIXTURES_DIR, file));
      const parsed = await parseRenewalPack(buf);
      expect(parsed.type).toBe('proportional');
      expect(parsed).toMatchSnapshot();
    });
  });

  describe.each(NP_FILES)('%s', (file) => {
    it('parses and matches snapshot', async () => {
      const buf = fs.readFileSync(path.join(FIXTURES_DIR, file));
      const parsed = await parseRenewalPack(buf);
      expect(parsed.type).toBe('non_proportional');
      expect(parsed).toMatchSnapshot();
    });
  });

  it('classifies sheets containing "Treaty Layers" as non_proportional', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'NP_01.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.type).toBe('non_proportional');
    expect(parsed.sheets.treatyLayers).toBeDefined();
    expect(parsed.sheets.treatyLayers.length).toBeGreaterThan(0);
  });

  it('classifies workbooks with EGNPI sheet as non_proportional', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'NP_01.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.sheets.egnpi).toBeDefined();
  });

  it('falls back to proportional when neither indicator is present', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_01.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.type).toBe('proportional');
  });

  it('preserves unknown sheets without throwing', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_04.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.unknown.length).toBeGreaterThan(0);
    expect(parsed.unknown[0]).toHaveProperty('name');
    expect(parsed.unknown[0]).toHaveProperty('rows');
  });

  it('produces triangle output with matching uwYears / devPeriods / values shape', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_01.xlsx'));
    const parsed = await parseRenewalPack(buf);
    const tri = parsed.sheets.premiumTriangle;
    expect(tri).toBeDefined();
    expect(Array.isArray(tri.uwYears)).toBe(true);
    expect(Array.isArray(tri.devPeriods)).toBe(true);
    expect(tri.values.length).toBe(tri.uwYears.length);
    for (const row of tri.values) expect(row.length).toBe(tri.devPeriods.length);
  });

  it('extracts treaty layers with the spec field shape', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'NP_02.xlsx'));
    const parsed = await parseRenewalPack(buf);
    const [first] = parsed.sheets.treatyLayers;
    expect(first).toEqual(
      expect.objectContaining({
        layer: expect.any(String),
        limit: expect.any(Number),
        attachment: expect.any(Number),
        aggLimit: expect.any(Number),
        egnpi: expect.any(Number),
        rate: expect.any(Number),
        earnedPremium: expect.any(Number),
        mdp: expect.any(Number),
        mdpAlt: expect.any(Number),
        reinstatements: expect.any(Number),
        reinstatementPct: expect.any(Number),
      }),
    );
  });

  it('extracts cedant and classes from the Cover sheet', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_02.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.cedant).toBe('Beta Re');
    expect(parsed.classes).toEqual(['Property']);
  });

  it('reports the uwYearRange spanning across triangles, losses and EGNPI', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_04.xlsx'));
    const parsed = await parseRenewalPack(buf);
    const [lo, hi] = parsed.uwYearRange;
    expect(lo).toBeLessThanOrEqual(hi);
    expect(lo).toBeGreaterThanOrEqual(1900);
    expect(hi).toBeLessThanOrEqual(2200);
  });

  // ── triangle header handling (F71 / F72 / F73) ──────────────────
  async function buildWorkbook(sheetName, rows) {
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet(sheetName);
    rows.forEach((r) => ws.addRow(r));
    return Buffer.from(await wb.xlsx.writeBuffer());
  }

  it('keeps values aligned to their own header columns when a non-numeric column sits mid-triangle (F71)', async () => {
    // A 'Total' column between the dev columns. Hand expectation:
    // dev 12 → 1000, dev 24 → 800; the Total value (1800) must be ignored,
    // NOT shifted onto dev 24 — the old positional read booked 1800 at 24
    // and silently dropped the true 800.
    const buf = await buildWorkbook('Premium Triangle', [
      ['UW Year', 12, 'Total', 24],
      [2020, 1000, 1800, 800],
    ]);
    const parsed = await parseRenewalPack(buf);
    expect(parsed.sheets.premiumTriangle).toEqual({
      uwYears: [2020],
      devPeriods: [12, 24],
      values: [[1000, 800]],
    });
    // ...and the skipped header is announced, never silent.
    expect(parsed.warnings).toContain(
      'Triangle in "Premium Triangle": ignored non-development column "Total"',
    );
  });

  it('round-trips the tool\'s own export dev labels — \'DY 1\' style (F72)', async () => {
    // renewalPackExport/builder.js devLabel writes 'DY n' for whole dev
    // years and '<m>m' otherwise; a pack this system produced must come
    // back with its triangle intact, not as devPeriods: [] with every
    // value silently dropped.
    const buf = await buildWorkbook('Premium Triangle', [
      ['UW Year', 'DY 1', 'DY 2', '30m'],
      [2020, 1000, 1800, 2100],
      [2021, 1200, null, null],
    ]);
    const parsed = await parseRenewalPack(buf);
    expect(parsed.sheets.premiumTriangle).toEqual({
      uwYears: [2020, 2021],
      devPeriods: [12, 24, 30], // DY 1 → 12, DY 2 → 24, '30m' → 30
      values: [[1000, 1800, 2100], [1200, null, null]],
    });
    expect(parsed.warnings).toEqual([]);
  });

  it('parses \'Dev 1\' / \'Year 2\' label variants and warns on a truly unparseable header', async () => {
    const buf = await buildWorkbook('Claims Triangle', [
      ['UW Year', 'Dev 1', 'Year 2', 'Ultimate'],
      [2022, 500, 700, 900],
    ]);
    const parsed = await parseRenewalPack(buf);
    expect(parsed.sheets.claimsTriangle).toEqual({
      uwYears: [2022],
      devPeriods: [12, 24],
      values: [[500, 700]],
    });
    expect(parsed.warnings).toContain(
      'Triangle in "Claims Triangle": ignored non-development column "Ultimate"',
    );
  });

  it('classifies an \'Outstanding Claims Triangle\' sheet as OS, not paid (F73)', async () => {
    const buf = await buildWorkbook('Outstanding Claims Triangle', [
      ['UW Year', 12, 24],
      [2020, 500, 300],
    ]);
    const parsed = await parseRenewalPack(buf);
    expect(parsed.sheets.osClaimsTriangle).toEqual({
      uwYears: [2020],
      devPeriods: [12, 24],
      values: [[500, 300]],
    });
    expect(parsed.sheets.claimsTriangle).toBeUndefined();
  });

  it('still classifies \'OS Claims Triangle\' as OS and \'Claims Triangle\' as paid', async () => {
    const os = await parseRenewalPack(await buildWorkbook('OS Claims Triangle', [
      ['UW Year', 12], [2020, 500],
    ]));
    expect(os.sheets.osClaimsTriangle).toBeDefined();
    expect(os.sheets.claimsTriangle).toBeUndefined();

    const paid = await parseRenewalPack(await buildWorkbook('Claims Triangle', [
      ['UW Year', 12], [2020, 400],
    ]));
    expect(paid.sheets.claimsTriangle).toBeDefined();
    expect(paid.sheets.osClaimsTriangle).toBeUndefined();
  });

  // ── resource caps (I4) ──────────────────────────────────────────
  it('rejects a workbook that declares more worksheets than the cap', async () => {
    const wb = new ExcelJS.Workbook();
    // 51 sheets > MAX_SHEETS (50). Cheap to build, hits the cap before any
    // per-cell materialization happens.
    for (let i = 0; i < 51; i++) wb.addWorksheet(`Sheet ${i + 1}`);
    const buf = await wb.xlsx.writeBuffer();
    await expect(parseRenewalPack(Buffer.from(buf))).rejects.toThrow(/too many worksheets/i);
  });

  it('accepts a small workbook that stays within the caps', async () => {
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Cover');
    ws.addRow(['Cedant', 'Test Re']);
    const buf = await wb.xlsx.writeBuffer();
    await expect(parseRenewalPack(Buffer.from(buf))).resolves.toBeDefined();
  });
});
