// Snapshot tests for the renewal-pack parser.
//
// Fixtures live at <repo>/test/fixtures/renewal-packs/ and are generated by
// server/scripts/generate-renewal-pack-fixtures.js. Snapshots are committed
// so a behavioural drift in the parser surfaces as a test failure rather
// than a silent change in production output.

import { describe, it, expect } from 'vitest';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { parseRenewalPack } from './parser.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// vitest runs from server/, so fixtures are two levels up.
const FIXTURES_DIR = path.resolve(__dirname, '../../../../test/fixtures/renewal-packs');

const PROP_FILES = Array.from({ length: 10 }, (_, i) => `PROP_${String(i + 1).padStart(2, '0')}.xlsx`);
const NP_FILES = Array.from({ length: 10 }, (_, i) => `NP_${String(i + 1).padStart(2, '0')}.xlsx`);

describe('parseRenewalPack', () => {
  it('locates the fixtures directory', () => {
    expect(fs.existsSync(FIXTURES_DIR)).toBe(true);
  });

  describe.each(PROP_FILES)('%s', (file) => {
    it('parses and matches snapshot', async () => {
      const buf = fs.readFileSync(path.join(FIXTURES_DIR, file));
      const parsed = await parseRenewalPack(buf);
      expect(parsed.type).toBe('proportional');
      expect(parsed).toMatchSnapshot();
    });
  });

  describe.each(NP_FILES)('%s', (file) => {
    it('parses and matches snapshot', async () => {
      const buf = fs.readFileSync(path.join(FIXTURES_DIR, file));
      const parsed = await parseRenewalPack(buf);
      expect(parsed.type).toBe('non_proportional');
      expect(parsed).toMatchSnapshot();
    });
  });

  it('classifies sheets containing "Treaty Layers" as non_proportional', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'NP_01.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.type).toBe('non_proportional');
    expect(parsed.sheets.treatyLayers).toBeDefined();
    expect(parsed.sheets.treatyLayers.length).toBeGreaterThan(0);
  });

  it('classifies workbooks with EGNPI sheet as non_proportional', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'NP_01.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.sheets.egnpi).toBeDefined();
  });

  it('falls back to proportional when neither indicator is present', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_01.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.type).toBe('proportional');
  });

  it('preserves unknown sheets without throwing', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_04.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.unknown.length).toBeGreaterThan(0);
    expect(parsed.unknown[0]).toHaveProperty('name');
    expect(parsed.unknown[0]).toHaveProperty('rows');
  });

  it('produces triangle output with matching uwYears / devPeriods / values shape', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_01.xlsx'));
    const parsed = await parseRenewalPack(buf);
    const tri = parsed.sheets.premiumTriangle;
    expect(tri).toBeDefined();
    expect(Array.isArray(tri.uwYears)).toBe(true);
    expect(Array.isArray(tri.devPeriods)).toBe(true);
    expect(tri.values.length).toBe(tri.uwYears.length);
    for (const row of tri.values) expect(row.length).toBe(tri.devPeriods.length);
  });

  it('extracts treaty layers with the spec field shape', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'NP_02.xlsx'));
    const parsed = await parseRenewalPack(buf);
    const [first] = parsed.sheets.treatyLayers;
    expect(first).toEqual(
      expect.objectContaining({
        layer: expect.any(String),
        limit: expect.any(Number),
        attachment: expect.any(Number),
        aggLimit: expect.any(Number),
        egnpi: expect.any(Number),
        rate: expect.any(Number),
        earnedPremium: expect.any(Number),
        mdp: expect.any(Number),
        mdpAlt: expect.any(Number),
        reinstatements: expect.any(Number),
        reinstatementPct: expect.any(Number),
      }),
    );
  });

  it('extracts cedant and classes from the Cover sheet', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_02.xlsx'));
    const parsed = await parseRenewalPack(buf);
    expect(parsed.cedant).toBe('Beta Re');
    expect(parsed.classes).toEqual(['Property']);
  });

  it('reports the uwYearRange spanning across triangles, losses and EGNPI', async () => {
    const buf = fs.readFileSync(path.join(FIXTURES_DIR, 'PROP_04.xlsx'));
    const parsed = await parseRenewalPack(buf);
    const [lo, hi] = parsed.uwYearRange;
    expect(lo).toBeLessThanOrEqual(hi);
    expect(lo).toBeGreaterThanOrEqual(1900);
    expect(hi).toBeLessThanOrEqual(2200);
  });
});
