-- Seed 001: UW Roles — intentionally a no-op (audit F113).
--
-- The role taxonomy is owned by the MIGRATIONS, not this seed: 034 seeds the
-- role_code'd hierarchy (CE/CU/TD/TM/...), 118 extends it (CA/UM/UW/AN) and
-- 143 adds RM — nine roles in total, each with role_code, hierarchy_level and
-- can_override_below, upserted ON CONFLICT (role_name) so they self-heal on
-- every migrate.
--
-- This file previously inserted a stale PARALLEL role model (UNDERWRITER /
-- UW_MANAGER / CHIEF_UNDERWRITER) with role_code NULL and the default
-- hierarchy_level 10 + can_override_below true — giving CHIEF_UNDERWRITER
-- (authority_limit_usd NULL = unlimited) unbounded authority, and NULL-code
-- rows that role_code-branching logic (e.g. seedTestTreaties' underwriter/
-- approver split) misclassifies. Rather than maintain a second copy of the
-- taxonomy here, the seed defers to the migrations entirely.
--
-- seeds/run.js still executes this file (comment-only SQL is a valid empty
-- query), so the seed pipeline is unchanged: run migrations first, then
-- `npm run seed` populates reference data via 002.
