# -*- coding: utf-8 -*-
# Checklist content for the Universe 3 enterprise-readiness review.
# Each item: (id, priority, title, look_at, done_when)

SECTIONS = []

def S(num, title, blurb, items):
    SECTIONS.append({"num": num, "title": title, "blurb": blurb, "items": items})

# ───────────────────────────────────────────────────────────────────────────
S("0", "Set Up And Reproduce The Baseline",
  "Do not review from reading alone. Get every gate running locally first, so that every finding "
  "you raise later can be demonstrated, and every fix you propose can be proven.",
[
 ("0.1","P1","Run the full verification gate end to end",
  "`npm run verify` (lint + typecheck + frontend budget + server tests + client build + client coverage)",
  "The whole gate passes on a clean checkout of `main`. Record wall-clock time and any flaky test."),
 ("0.2","P1","Run the DB-backed integration suite",
  "`scripts/test-db.sh`; `server/tests/integration/*`; CI's `integration` job in `.github/workflows/ci.yml`",
  "Integration tests run with `TEST_WITH_DB=1` and the coverage thresholds in `server/vitest.config.js` are met."),
 ("0.3","P2","Stand the stack up from the container manifests",
  "`docker compose up --build`; `Dockerfile`; `Dockerfile.jobs`; `docker-compose.yml`",
  "App and Postgres come up, migrations apply, `/api/health/deep` returns `status: ok`."),
 ("0.4","P2","Diff the deployed configuration against the sample",
  "`render.yaml` vs `.env.example` (14 KB of documented flags); `server/src/config/env.js`",
  "You have a written list of every env var that production sets, omits, or overrides — this is where most findings live."),
 ("0.5","P2","Read the prior audits before duplicating work",
  "`docs/CODEBASE_AUDIT_2026-08.md`, `docs/CODEBASE_AUDIT_2026-07.md`, `SECURITY.md`",
  "Each prior finding is marked verified-fixed, still-open, or regressed. See Appendix A."),
 ("0.6","P3","Capture a code-size and hot-spot baseline",
  "`find client/src server/src -name '*.js*' | xargs wc -l | sort -rn | head -30`",
  "You can name the ten largest modules and why each is large — they set the refactor agenda."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("1", "Authentication And Login",
  "The login path is the single highest-value surface in the system. Trace every way a session can be "
  "created, and prove that no path mints one without a verified credential.",
[
 ("1.1","P1","Enumerate every path that can create a session",
  "`server/src/routes/auth.js` (POST /auth/login, /auth/name-login, POST /auth/users), `server/src/routes/sso.js`, `server/src/services/sessions.js`",
  "You have a complete, written list of session-minting entry points. Any path that does not verify a secret is a blocker."),
 ("1.2","P1","Audit the passwordless `name-login` pilot flag",
  "`ALLOW_NAME_AUTH` in `render.yaml`; the `/auth/name-login` handler in `server/src/routes/auth.js`",
  "Either the flag is off in production, or a boot-time fence in `config/env.js` refuses to start with it on in production — mirroring `checkDemoAuthConfig`. See A1."),
 ("1.3","P1","Audit the demo-auth backdoor fence",
  "`checkDemoAuthConfig` in `server/src/config/env.js`; `ALLOW_DEMO_AUTH` reads in `middleware/requestContext.js`",
  "`ALLOW_DEMO_AUTH=true` with `NODE_ENV=production` is a fatal boot error, and the `demo2026` shortcut is unreachable in production. Confirm by test, not by comment."),
 ("1.4","P1","Confirm no route trusts `x-user-*` headers for authorization",
  "`demoUserFromHeaders` in `server/src/middleware/requestContext.js`; grep the whole server for `x-user-`",
  "Header identity is reachable only under `ALLOW_DEMO_AUTH`; every other read of those headers is logging-only."),
 ("1.5","P1","Review the public (unauthenticated) endpoint allow-list",
  "The `PUBLIC_AUTH` set in `server/src/routes/auth.js`",
  "Every entry is justified in writing. `GET /auth/users` returning the full roster with role codes to anonymous callers is an enumeration finding — see A2."),
 ("1.6","P1","Verify password hashing parameters and rehash-on-login",
  "`server/src/lib/passwordHash.js`, `PASSWORD_SCRYPT_COST`; `needsRehash` usage in `routes/auth.js`",
  "scrypt is async (off the event loop), cost is tuned to the production instance size, and logins transparently upgrade legacy hashes."),
 ("1.7","P1","Test the password policy at every place a password is set",
  "`validatePasswordStrength` in `server/src/routes/auth.js`; change-password, admin-create, self-register, SSO provisioning",
  "One shared policy gates all paths. No path can set a password that another path would reject."),
 ("1.8","P1","Hunt for seeded or shared credentials in migrations and seeds",
  "`server/src/db/migrations/132_saudi_re_demo_personas.sql`; `server/src/db/seeds/`; `git log -S password`",
  "No migration that runs in production installs a known password or clears `must_change_password`. See A3."),
 ("1.9","P1","Prove brute-force controls actually engage",
  "Login limiter in `server/src/app.js` (IP + submitted identity, 5 per 15 min); `failed_attempts` / `locked_until` in `routes/auth.js`",
  "You have driven a lockout and a rate-limit rejection by hand. Note that neither engages on a login path that never fails."),
 ("1.10","P1","Check limiter counting under multiple instances",
  "`server/src/lib/rateLimitStore.js`; `REDIS_URL`; `rateLimitStoreEnabled()` in `startup/productionPosture.js`",
  "Either a shared Redis store is configured, or the deployment is provably single-instance and that is a documented constraint."),
 ("1.11","P2","Verify limiter bypass flags cannot exist in production",
  "`LOAD_TEST` / `ALLOW_DEMO_AUTH` bypass in `server/src/app.js` (~line 173)",
  "The bypass is fenced by the same production check as the auth backdoor, not only by a warning log."),
 ("1.12","P1","Review the SSO/OIDC integration end to end",
  "`server/src/routes/sso.js`, `services/identity/oidcClient.js`, `provisioning.js`, `backchannelLogout.js`, `lib/ssoStateCookie.js`",
  "State and nonce are validated, the ID token signature and issuer/audience are checked, and the redirect URI is allow-listed — no open redirect."),
 ("1.13","P1","Verify MFA is enforced by the application, not assumed from the IdP",
  "`IDENTITY_REQUIRED_ACR` / `IDENTITY_REQUIRED_AMR` / `IDENTITY_ENFORCE_MFA` in `server/src/config/identity.js`",
  "With `IDENTITY_ENFORCE_MFA` on, an SSO config lacking acr/amr requirements is a fatal boot error, and a token missing the required claim is rejected."),
 ("1.14","P1","Review claim-to-role mapping for privilege escalation",
  "`mapClaimsToRole` in `server/src/config/identity.js`; `IDENTITY_ROLE_MAP`, `IDENTITY_DEFAULT_ROLE`",
  "An unknown, missing, or attacker-influenced claim can only ever yield the lowest-privilege role. Write a test for the adversarial claim shapes."),
 ("1.15","P2","Review the break-glass local-admin path",
  "`isBreakGlassUser` / `IDENTITY_BREAK_GLASS_USERS` in `server/src/config/identity.js`; `docs/runbooks/sso-mfa-break-glass.md`",
  "The list is short, named, audited on use, alerted on, and reviewed on a stated cadence."),
 ("1.16","P2","Check open self-registration is off and cannot self-elevate",
  "`ALLOW_OPEN_REGISTRATION` in `render.yaml`; the `POST /auth/users` self-gate in `routes/auth.js`",
  "Registration is off in production; when on, a new account cannot choose its own role or hierarchy level."),
 ("1.17","P2","Confirm the forced-password-change gate cannot be walked around",
  "`server/src/app.passwordGate.test.js`; `mustChangePassword` in `middleware/requestContext.js`",
  "A `must_change_password` user is blocked from all mutations, not merely redirected by the client."),
 ("1.18","P2","Review login-failure responses for user enumeration",
  "Error bodies and timing in the `/auth/login` handler",
  "Unknown-user and wrong-password return the same status, body, and broadly the same latency."),
 ("1.19","P2","Confirm security-relevant auth events are alerted, not just logged",
  "`server/src/services/securityAlerts.js`; `emitSecurityAlert` call sites",
  "Lockouts, break-glass logins, mass revocations and posture errors reach a channel a human actually watches."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("2", "Sessions, Tokens And Cookies",
  "A correct login is worthless if the resulting session cannot be revoked, or can be replayed.",
[
 ("2.1","P1","Verify token signing, algorithm and secret strength",
  "`server/src/lib/authToken.js`; the `validateEnv()` secret gate in `server/src/config/env.js`",
  "The algorithm is pinned (no `none`/`alg` confusion), the secret is >=32 chars, and boot fails without it in production."),
 ("2.2","P1","Confirm role and mandate are re-read per request, not carried in the token",
  "`loadUserAndSession` in `server/src/middleware/requestContext.js`; the `v_user_mandate` view",
  "A demotion, deactivation or COB restriction takes effect on the very next request with an existing token."),
 ("2.3","P1","Test session revocation and the mass-revoke epoch",
  "`server/src/services/sessions.js` (`revokeSession`, `revokeAllForUser`); `uw_user.session_epoch`",
  "Logout, password change, role change and deactivation each invalidate live sessions immediately. Prove it with a held cookie."),
 ("2.4","P1","Review cookie attributes",
  "`server/src/lib/authCookies.js` (`AUTH_COOKIE`, `CSRF_COOKIE`)",
  "`HttpOnly`, `Secure`, `SameSite`, `Path` and domain are correct for production, and the CSRF cookie is deliberately readable while the auth cookie is not."),
 ("2.5","P1","Test CSRF double-submit protection on every mutating route",
  "`server/src/lib/csrf.js`; `csrfProtection` wiring in `app.js`; `CSRF_HEADER`",
  "A cookie-authenticated POST/PUT/PATCH/DELETE without a matching header token is rejected. Check for routes mounted outside the guard."),
 ("2.6","P2","Review session lifetime and idle handling",
  "`SESSION_TTL_HOURS` (8 in `render.yaml`); `auth_session.expires_at`",
  "Absolute and idle lifetimes are deliberate and documented; expiry is enforced server-side, not by cookie max-age alone."),
 ("2.7","P2","Check OIDC back-channel logout closes local sessions",
  "`server/src/services/identity/backchannelLogout.js`",
  "An IdP-initiated logout revokes the matching local `auth_session` rows; the endpoint verifies the logout token."),
 ("2.8","P2","Confirm the session table is bounded",
  "`auth_session` schema and any cleanup job; `server/src/db/maintenance/`",
  "Expired and revoked sessions are purged on a schedule; the table cannot grow without limit."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("3", "Authorization, Roles And Mandates",
  "Six role codes (CE, CU, TD, TM, TUW/UW) and a hierarchy level drive edit rights, approvals and "
  "underwriting limits. Authorization must be enforced server-side on every route.",
[
 ("3.1","P1","Map every route to its guard",
  "`server/src/routes/registerApiRoutes.js`; `requireAuth`, `requireMinLevel` in `middleware/requestContext.js`",
  "You have a route-by-route table showing the auth and role guard on each. Every unguarded route is justified in writing."),
 ("3.2","P1","Verify the global mutation guard cannot be bypassed",
  "`guardApiMutations` in `server/src/services/permissions.js`; its mount order in `app.js`",
  "Routers mounted before or outside the guard are identified; none permits a write."),
 ("3.3","P1","Test the ownership / edit-lock rule adversarially",
  "`computeEditPermission` and `assertCanEdit` in `server/src/services/permissions.js`",
  "Only the current assignee may mutate a contract, quote or fac risk; hierarchy level does not silently grant edit. Attempt cross-user writes by ID."),
 ("3.4","P1","Probe for insecure direct object references",
  "Any route taking `:id` — `routes/treaties.js`, `quotes.js`, `facultative.js`, `dashboard.js`, `workbench.js`",
  "Fetching another user's or another entity's ID either 403s or filters by mandate; it never leaks by ID guessing."),
 ("3.5","P1","Verify approval authority and underwriting limits are server-enforced",
  "`server/src/services/approvals.js`, `workflow.js`, `quoteWorkflow.js`, `quoteBind.js`; `effective_limit_usd`",
  "A user cannot approve or bind above their mandate limit even with a hand-crafted request. The client's own gating is not the control."),
 ("3.6","P2","Check class-of-business and treaty-type restrictions are applied in queries",
  "`restricted_cob_ids`, `treaty_type_scope` from `v_user_mandate`; their use in repositories",
  "Restrictions are applied in the SQL predicate, not filtered in the client or after serialization."),
 ("3.7","P2","Review the state machine for illegal transitions",
  "`server/src/lib/statusMachine.js`; `services/workflowTransition.test.js`; `docs/pricing-signoff-required.md`",
  "Every transition is validated server-side; SIGNED / DECLINED / NTU are terminal; sign-off cannot be skipped."),
 ("3.8","P2","Confirm admin and reference-data routes are level-gated",
  "`server/src/routes/facultativeReference.js`; `services/facReferenceAdminService.js`; `client/src/screens/admin`",
  "Rate tables and reference data can only be changed by the intended roles, and every change is audited and versioned."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("4", "Application Security Controls",
  "Headers, input, output, uploads and outbound calls.",
[
 ("4.1","P1","Review the Content-Security-Policy and its nonce plumbing",
  "`server/src/app.js` (helmet config, `res.locals.cspNonce`, `serveIndex`); `server/src/app.csp.test.js`; `SECURITY.md`",
  "The policy is enforcing (not report-only), has no `unsafe-inline`/`unsafe-eval` for scripts, and the nonce is per-request and unpredictable."),
 ("4.2","P1","Review CORS for production",
  "`createCorsOptions` in `server/src/app.js`; `CORS_ORIGIN` in `render.yaml`",
  "Production uses an explicit allow-list; origin reflection with credentials is impossible in production. A `*` value is a finding."),
 ("4.3","P1","Verify input validation coverage across the API",
  "`server/src/validation/*` (zod schemas); `server/src/lib/validate.js`",
  "Every route with a body or query parameter has a schema. List the routes that do not — they are the injection and mass-assignment surface."),
 ("4.4","P1","Check for SQL injection and unsafe identifier interpolation",
  "Grep for template literals inside `pool.query`; note the interpolated table names in `services/permissions.js`",
  "All user-supplied values are parameterized; any interpolated identifier comes from a fixed internal allow-list, never from a request."),
 ("4.5","P1","Review file upload handling",
  "`server/src/lib/uploadValidation.js`, `uploadStorage.js`; multer config; `UPLOAD_DIR`",
  "Type and size are validated by content and not by filename alone; stored names are non-guessable; path traversal is impossible; downloads are access-checked."),
 ("4.6","P1","Confirm durable upload storage in production",
  "`remoteStorageConfigured()` / `localUploadsAllowed()` in `lib/uploadStorage.js`; Cloudinary vars in `render.yaml`",
  "Either object storage is configured, or ephemeral local disk is an explicit, documented acceptance. As shipped this errors at boot — see A4."),
 ("4.7","P1","Stop internal error detail reaching clients",
  "`server/src/middleware/errorHandler.js` (~line 47)",
  "For `status >= 500` in production the client gets a generic message plus a request ID; the detail stays in the server log. See A5."),
 ("4.8","P2","Review outbound HTTP clients for SSRF and secret leakage",
  "`server/src/lib/axcoClient.js`, `googlePlaces.js`, `imfClient.js`, `worldBankClient.js`, `llmClient.js`, `facDocAi.js`",
  "Destinations are fixed or allow-listed, timeouts and retry caps are set, API keys never reach logs or client responses."),
 ("4.9","P1","Review the AI/LLM surface for prompt injection and data egress",
  "`server/src/lib/llmClient.js`, `aiGovernance.js`, `facDocAiPrompts.js`; `routes/ai.js`, `aiMarket.js`, `aiCedant.js`; `services/renewalPack/extractor.js`",
  "Untrusted document content cannot alter instructions or trigger tool/DB actions; what leaves the estate is documented and approved; AI routes are authenticated and rate-limited."),
 ("4.10","P2","Verify request timeouts and body-size limits",
  "`server/src/middleware/requestTimeout.js`; the `express.json` limit in `app.js`",
  "Slow and oversized requests are rejected with a clear code; limits are set for every parser including multipart."),
 ("4.11","P2","Check caching headers cannot leak per-user data",
  "`server/src/middleware/httpCache.js`; `cacheStats()`",
  "No authenticated, user-scoped response is publicly cacheable; the cache key includes identity wherever the payload is mandate-filtered."),
 ("4.12","P2","Review the container image posture",
  "`Dockerfile`, `.dockerignore`; `.github/workflows/image-security.yml` (Syft SBOM + Trivy)",
  "Non-root user, pinned base digest, no secrets in layers, no dev dependencies in the runtime image, and the Trivy gate actually fails the build."),
 ("4.13","P2","Confirm secret scanning and SAST are running and enforcing",
  "`.github/workflows/codeql.yml`; `SECURITY.md` (Static analysis & secret scanning)",
  "CodeQL runs on PRs and is required; the workflow's soft-fail path is not silently hiding that scanning is disabled."),
 ("4.14","P2","Verify database transport security is enforced, not assumed",
  "`server/src/db/pool.js`; `DATABASE_URL` in `render.yaml`; `DEPLOYMENT.md`",
  "An explicit `ssl` option is set in production, or boot asserts `sslmode=require` in the connection string. See A6."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("5", "Architecture And Code Structure",
  "Roughly 250 server modules and 400 client modules. Judge the boundaries, not the line count.",
[
 ("5.1","P1","Validate the documented architecture against the code",
  "`docs/architecture.md` (core model, quote/treaty duality, save pattern, guardrails)",
  "The document describes the system as it is today. Where it does not, either the code or the document is a finding."),
 ("5.2","P1","Assess layering discipline: routes, services, repositories",
  "`server/src/routes/` vs `services/` vs `modules/pricing/repositories/`",
  "Routes stay thin; business rules live in services; SQL lives in repositories. Record every route with inline SQL or business logic."),
 ("5.3","P1","Decide where the authoritative pricing calculation lives",
  "`client/src/utils/npPricingEngine.js` (983 lines), `shared/pricingMath.js`, `server/src/lib/pricingVerifier.js`, `PRICING_STRICT`",
  "A written decision: keep client-side computation with server drift rejection, or move the primary calculation server-side. The financial authority must not sit in a tamperable client. See A9."),
 ("5.4","P2","Review the module boundaries of the newer `modules/` code",
  "`server/src/modules/pricing/{controllers,services,repositories}`, `modules/gemVulnerability`, `modules/hazusVulnerability`",
  "The modular pattern is either the target for the whole server or explicitly scoped; two competing structures need a documented migration path."),
 ("5.5","P2","Identify god-modules and set a refactor agenda",
  "`client/src/components/cedant/CedantSummaryTabs.jsx` (2,066 lines), `MarketIntelligenceModal.jsx` (1,212), `server/src/routes/auth.js` (1,144)",
  "Each oversized module has an owner, a stated risk, and a split plan — or a documented reason to leave it alone."),
 ("5.6","P2","Confirm shared logic is genuinely shared",
  "`shared/pricingMath.js`, `shared/onLevel.js`, `shared/fac/`",
  "No formula is implemented twice with room to drift. Any duplicate is a correctness risk, not a style issue."),
 ("5.7","P2","Review concurrency and optimistic locking coverage",
  "`server/src/db/optimisticLock.js`, `withTransaction.js`; `docs/optimistic-locking-coverage.md`; `client/src/hooks/useEditLock.js`",
  "Every multi-step write is transactional; concurrent edits collide loudly rather than silently overwriting."),
 ("5.8","P2","Review the background-job architecture",
  "`server/src/jobs/refreshLdfBenchmarks.js`, `refreshFacAccumulation.js`; `.github/workflows/scheduled-jobs.yml`; Render Cron in `render.yaml`; `Dockerfile.jobs`",
  "Jobs are idempotent, safe to run concurrently, alert on failure, and are not silently skipped when a deploy fails."),
 ("5.9","P3","Make the tenancy decision explicit",
  "No `tenant_id` and no row-level security anywhere in `server/src/db/migrations/`",
  "`docs/architecture.md` states single-tenant deploy-per-customer as a deliberate choice, with the cost of changing it later."),
 ("5.10","P2","Assess API contract stability and versioning",
  "`server/src/routes/registerApiRoutes.js`; client fetch layer in `client/src/hooks/useResource.ts`",
  "There is a stated policy for breaking changes to `/api` — versioning, deprecation window, or a documented tight-coupling acceptance."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("6", "Data Layer, Migrations And Integrity",
  "140 forward-only migrations against Postgres. The schema is the asset; treat migration safety as a first-class concern.",
[
 ("6.1","P1","Review the migration runner for safety",
  "`server/src/startup/runMigrations.js`, `server/src/db/migrate.js`; `RUN_MIGRATIONS_ON_BOOT`; `preDeployCommand` in `render.yaml`",
  "Migrations are advisory-locked, transactional, and applied exactly once across concurrent instances."),
 ("6.2","P1","State the rollback policy explicitly",
  "140 migrations in `server/src/db/migrations/` with no `down` scripts; `docs/runbooks/disaster-recovery.md`",
  "Forward-only is written down as policy, with restore-from-backup as the stated recovery path and a rehearsed timing. See A10."),
 ("6.3","P1","Check for long-locking DDL in recent migrations",
  "`docs/migration-audit.md`; `docs/runbooks/validate-not-valid-fks.md`; recent files `133`–`140`",
  "Index creation is concurrent, constraints are added `NOT VALID` then validated, and no migration takes a long exclusive lock on a hot table."),
 ("6.4","P1","Verify referential integrity and constraints exist in the database",
  "`docs/database-design-audit.md`; foreign keys, `NOT NULL`, `CHECK` constraints across the schema",
  "Invariants are enforced by the database, not only by application code. List the ones that are application-only."),
 ("6.5","P2","Review connection-pool sizing against the deployment",
  "`server/src/db/pool.js`, `poolWatchdog.js`; `DB_POOL_MAX`/`DB_POOL_MIN`; `docs/scaling.md`",
  "`instances x DB_POOL_MAX` fits comfortably inside the database's `max_connections`, with headroom for jobs and migrations."),
 ("6.6","P2","Review numeric types used for money and rates",
  "Column types across the pricing tables; rounding in `shared/pricingMath.js`",
  "Monetary values use exact numeric types with a stated rounding convention; no float drift reaches a bound contract."),
 ("6.7","P2","Confirm N+1 queries and unbounded result sets are controlled",
  "`server/src/db/contractJoins.js`, `batchInsert.js`; pagination headers `X-Total-Count`/`X-Page`",
  "List endpoints paginate by default; no request can ask the database for an unbounded scan."),
 ("6.8","P2","Verify retention jobs run and are proven",
  "`server/scripts/cleanup-snapshots.js` (30-day `import_snapshots` window); `docs/data-retention.md`",
  "The nightly job is scheduled, monitored, and its last successful run is observable."),
 ("6.9","P3","Review materialized-view refresh strategy",
  "`server/src/jobs/refreshLdfBenchmarks.js`; `mv_ldf_benchmark_*`",
  "Refreshes are concurrent where possible, cannot pile up, and stale views are detectable."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("7", "Secrets And Configuration",
  "Most findings in a mature codebase live in configuration rather than code.",
[
 ("7.1","P1","Scan the full git history for committed secrets",
  "`git log -p | grep -iE 'secret|api[_-]?key|password|token'`; GitHub secret scanning",
  "No live credential exists in any commit. Anything found is rotated first, then removed from history."),
 ("7.2","P1","Verify fail-fast validation of required production config",
  "`validateEnv()` / `validateRuntimeEnv()` in `server/src/config/env.js`; `startup/bootstrap.js`",
  "A missing or weak `AUTH_TOKEN_SECRET`, or a missing `DATABASE_URL`, refuses to boot rather than degrading quietly."),
 ("7.3","P1","Review every boot-time posture warning as a decision",
  "`server/src/startup/productionPosture.js` (identity, uploads, CORS, Redis)",
  "Each warning or error the current production config produces is either fixed or has a signed-off, written acceptance."),
 ("7.4","P2","Confirm a secret rotation procedure exists and is rehearsed",
  "`AUTH_TOKEN_SECRET`, `DATABASE_URL`, Cloudinary, LLM and third-party keys; `docs/runbooks/incident-response.md`",
  "There is a documented, timed procedure for rotating each secret, including what it invalidates (rotating the token secret logs everyone out)."),
 ("7.5","P2","Check environment parity",
  "`.env.example` vs `render.yaml` vs `docker-compose.yml` vs `ecosystem.config.cjs`",
  "Every flag that changes security behaviour is set explicitly in production rather than relying on a default."),
 ("7.6","P2","Verify feature flags are enumerated with owners and expiry",
  "`PRICING_STRICT`, `ALLOW_NAME_AUTH`, `ALLOW_DEMO_AUTH`, `ALLOW_OPEN_REGISTRATION`, `ALLOW_LOCAL_UPLOADS`, `OTEL_ENABLED`, `LOAD_TEST`",
  "A single table lists each flag, its production value, its owner, and its removal date. Temporary pilot flags have a hard end date."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("8", "Dependencies And Supply Chain",
  "Two workspaces plus a root, with overrides already in use. Keep the runtime clean and the gate honest.",
[
 ("8.1","P1","Triage every outstanding advisory",
  "`npm audit` at root, `--prefix server`, `--prefix client`; CI's `prod dependency audit` job",
  "Runtime dependencies are clean at the CI threshold. Dev-only advisories (the current root highs are build-chain: `brace-expansion`, `postcss`, `nanoid`, `shell-quote`, `ip-address`) are listed with a rationale."),
 ("8.2","P2","Review the pinning and override strategy",
  "`overrides` in root `package.json` and `server/package.json`; `package-lock.json` committed",
  "Overrides exist to close advisories, are dated, and have a removal condition once upstream ships a fix."),
 ("8.3","P2","Verify the licence scan covers what ships",
  "CI `dependency license scan` job in `.github/workflows/ci.yml`",
  "Production dependencies of both workspaces are scanned and the allow-list is deliberate for a commercial, unlicensed product."),
 ("8.4","P2","Confirm the SBOM is produced and retained",
  "`.github/workflows/image-security.yml` (Syft)",
  "An SBOM is generated per image build and retrievable for any deployed version."),
 ("8.5","P2","Check the Node runtime is pinned and supported",
  "`.nvmrc`, `.node-version`, `engines` in `package.json`, the `Dockerfile` base image",
  "All four agree, and the version is on a supported LTS line for the expected life of the release."),
 ("8.6","P3","Review automated dependency updates",
  "Dependabot/Renovate configuration in `.github/`",
  "Updates arrive on a schedule with CI gating, rather than accumulating until a forced upgrade."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("9", "Observability And Operations",
  "You cannot run an enterprise system you cannot see.",
[
 ("9.1","P1","Verify tracing and metrics are enabled in production",
  "`OTEL_ENABLED` and the rest of the OTEL vars; `server/src/observability/telemetry.js`, `otelInit.js`, `httpMetrics.js`, `poolMetrics.js`; `docs/observability.md`",
  "Traces and metrics reach a real backend from production, and someone has opened the dashboard this month."),
 ("9.2","P1","Add log-level control",
  "`server/src/lib/logger.js` — no `LOG_LEVEL` threshold today",
  "Verbosity is controllable by environment variable so an incident can be turned up and cost turned down. See A8."),
 ("9.3","P1","Confirm logs never contain credentials or personal data",
  "`logger.js` redaction; log lines in `routes/auth.js`, `middleware/requestContext.js`, the outbound clients",
  "Passwords, tokens, cookies, and API keys are impossible to log. Verify by grepping a real log sample, not by reading the redaction list."),
 ("9.4","P2","Verify request correlation end to end",
  "`server/src/middleware/requestId.js`; `X-Request-Id` in `EXPOSED_HEADERS`; client error surfacing",
  "A user-visible error carries an ID that finds the exact server log line and trace."),
 ("9.5","P1","Check health endpoints are wired to the platform",
  "`/api/health`, `/api/health/deep` in `app.js`; `healthCheckPath` in `render.yaml`",
  "The load balancer uses the shallow check; the deep check is monitored separately and its `X-Pool-Waiting` value is alerted on."),
 ("9.6","P1","Define alerting and on-call",
  "`docs/runbooks/incident-response.md`; `services/securityAlerts.js`",
  "There is a named alert for error rate, latency, pool saturation, job failure and boot-posture errors, each routed to someone on call."),
 ("9.7","P2","Review business-level metrics",
  "`server/src/observability/businessMetrics.js`, `aiMetrics.js`",
  "Quote, bind and pricing-drift volumes are observable, so a functional regression is visible before a customer reports it."),
 ("9.8","P2","Confirm graceful shutdown behaves under real deploys",
  "`server/src/startup/gracefulShutdown.js`; keep-alive tuning in `bootstrap.js`",
  "A SIGTERM during load drains in-flight requests without dropped connections. Prove it under `k6`."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("10", "Reliability, Availability And Recovery",
  "Enterprise buyers ask for numbers here, and expect evidence behind them.",
[
 ("10.1","P1","State the availability topology honestly",
  "`plan: starter`, single instance, no `numInstances` in `render.yaml`",
  "The absence of HA is either fixed (multiple instances behind the load balancer) or documented as an accepted limitation with its downtime implications. See A11."),
 ("10.2","P1","Prove backups exist and restores work",
  "`docs/backup-recovery.md` (RPO/RTO commitments); the restore-verification drill in `.github/workflows/scheduled-jobs.yml`",
  "A restore has been performed within the last quarter, timed, and the measured time is inside the committed RTO."),
 ("10.3","P1","Rehearse the disaster-recovery runbook",
  "`docs/runbooks/disaster-recovery.md`",
  "Someone who did not write the runbook has followed it end to end successfully, and the gaps they hit are fixed."),
 ("10.4","P2","Verify scale-out prerequisites before they are needed",
  "`REDIS_URL` for shared rate limits; upload storage; `docs/scaling.md`; `ecosystem.config.cjs`",
  "Every per-process assumption is listed, and each has a shared-state answer before a second instance is added."),
 ("10.5","P2","Check deploy and rollback procedure",
  "`deploy.sh`, `render.yaml` (`preDeployCommand`), `DEPLOYMENT.md`",
  "Rollback is one documented step, and its interaction with forward-only migrations is stated."),
 ("10.6","P2","Confirm timeouts and failure handling for third-party outages",
  "The outbound clients in `server/src/lib/`",
  "An outage at any third party degrades a feature, never the whole application."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("11", "Performance And Scale",
  "Measure before optimising, and re-measure after any change made from this checklist.",
[
 ("11.1","P1","Run the load tests and record a capacity baseline",
  "`npm run loadtest`, `loadtest:10vu`, `loadtest:capacity`; `load-test/k6/`; `loadtest:summarize`",
  "You have p50/p95/p99 latency and error rate at a stated concurrency, and know the level at which the service degrades."),
 ("11.2","P1","Profile the slowest endpoints against real data volumes",
  "`EXPLAIN ANALYZE` on the heaviest queries; `docs/scaling.md`",
  "The top five slowest endpoints are identified with an index or query plan for each. Test against production-scale row counts, not seed data."),
 ("11.3","P2","Verify the frontend bundle budget is meaningful",
  "`npm run budget:frontend`, `scripts/frontend-budget.mjs`; lazy route loading",
  "The budget reflects a real target on a real network, and it fails the build when exceeded."),
 ("11.4","P2","Check pool saturation behaviour under load",
  "`poolWatchdog.js`; `X-Pool-Waiting` from `/api/health/deep`",
  "Under the capacity test the pool does not queue sustainedly; if it does, `DB_POOL_MAX` and instance count are re-derived."),
 ("11.5","P2","Review heavy computation on the request path",
  "Pricing, clustering and export paths — `client/src/logic/portfolioClustering.js`, `services/renewalPackExport/`, `exceljs` use",
  "Long-running work is bounded, streamed, or moved off the request path; it cannot block the event loop."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("12", "Testing And Delivery Pipeline",
  "Around 2,000 server and 1,000 client tests already exist. Judge what they cover, not how many there are.",
[
 ("12.1","P1","Check coverage where the money is",
  "`server/vitest.config.js` thresholds; client coverage floors; `client/src/utils/npPricingEngine.js`",
  "Auth, workflow, pricing and document paths meet their per-area floors. Client coverage (~52% statements) covers the pricing engine specifically. See A12."),
 ("12.2","P1","Confirm CI gates are required, not advisory",
  "Branch protection on `main`; the four workflows in `.github/workflows/`",
  "A pull request cannot merge with a failing lint, test, audit, integration or CodeQL job."),
 ("12.3","P1","Verify negative and adversarial test cases exist for auth",
  "`server/src/routes/auth.test.js`, `sso.test.js`, `app.rateLimit.test.js`, `app.passwordGate.test.js`, `middleware/requestContext.test.js`",
  "Tests assert what must be *rejected* — forged tokens, revoked sessions, missing CSRF, elevated claims — not only the happy path."),
 ("12.4","P2","Review the golden-master pricing tests",
  "`client/src/screens/facultative/pricing/FacPricing.goldenMaster.test.jsx`; `server/src/lib/pricing.goldenMaster.test.js`; `npm run golden:fac`",
  "Regenerating a golden master is a deliberate, reviewed act — a diff in these files must never be rubber-stamped."),
 ("12.5","P2","Check for flaky and skipped tests",
  "Grep for `.skip`, `.todo`, `only`; run the suite three times",
  "No test is skipped without a linked ticket; the suite is deterministic."),
 ("12.6","P2","Confirm CI actions are pinned and least-privilege",
  "SHA pins and `permissions:` blocks in `.github/workflows/*.yml`",
  "Every third-party action is pinned to a SHA and the default token permission is read-only."),
 ("12.7","P3","Assess end-to-end coverage of the critical user journey",
  "Quote to pricing to approval to bind; `docs/ux-testing-protocol.md`",
  "At least one automated test walks the full revenue path against a real database."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("13", "Compliance, Privacy And Audit Trail",
  "Reinsurance pricing carries commercially sensitive counterparty data. The audit trail is a product feature.",
[
 ("13.1","P1","Verify every state-changing action is audited",
  "`server/src/services/audit.js`, `lib/mutationAudit.js`, `services/auditActor.test.js`, `contractHistory.js`",
  "Actor, action, entity, before/after and timestamp are captured for every mutation. Find the mutations that are not audited."),
 ("13.2","P1","Confirm the audit log is tamper-evident",
  "The audit table's permissions and any update/delete paths",
  "Application credentials cannot update or delete audit rows; retention is defined and enforced."),
 ("13.3","P1","Review the personal-data inventory against the schema",
  "`docs/data-retention.md`; `server/scripts/anonymize-user.js` (`gdpr:anonymize-user`)",
  "Every column holding personal data is listed, with a lawful basis, a retention period, and a tested erasure path."),
 ("13.4","P2","Verify data export and portability paths are access-controlled",
  "`services/renewalPackExport/`, `exceljs` exports, `routes/finance.js`, `financePush.js`",
  "An export contains only what the requesting user's mandate permits, and every export is audited."),
 ("13.5","P2","Confirm AI processing is governed",
  "`server/src/lib/aiGovernance.js`, `validateAiProviderConfig` in `app.js`",
  "Which data leaves the estate, to which provider, under what contract and retention terms, is written down and matches the code."),
 ("13.6","P2","Check vulnerability disclosure and response",
  "`SECURITY.md` (Reporting a vulnerability); `docs/runbooks/incident-response.md`",
  "There is a monitored contact, a stated response time, and an owner."),
 ("13.7","P3","Review access-review cadence",
  "`uw_user` roles and mandates; break-glass list",
  "Someone reviews who holds CE/CU and break-glass access on a stated schedule, with evidence retained."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("14", "Frontend Review",
  "Half the codebase, and the half where pricing is currently computed.",
[
 ("14.1","P1","Confirm the client enforces nothing security-relevant on its own",
  "Role checks in `client/src/screens/` and `components/`",
  "Every client-side gate has a server-side equivalent. The client is a convenience layer, never the control."),
 ("14.2","P1","Check for secrets and privileged data in the bundle",
  "`client/dist` after `npm run build`; `import.meta.env` usage",
  "No API key, internal hostname or privileged configuration ships to the browser."),
 ("14.3","P1","Review rendering of untrusted content",
  "Grep for `dangerouslySetInnerHTML`; imported spreadsheet and document content; `ExcelImportAgent.jsx`",
  "Imported or AI-extracted content is escaped, and the CSP would contain any miss."),
 ("14.4","P2","Verify error and session handling in the client",
  "`client/src/hooks/useResource.ts`, `useToast.js`, `useScreenSave.js`",
  "A 401 or 403 leads to a clean re-authentication; a failed save never silently discards user work."),
 ("14.5","P2","Review unsaved-state handling across navigation",
  "`useScreenSave.js`, `useEditLock.js`; the recent sidebar-navigation fix (commit `80c1903`)",
  "Navigating away cannot silently discard edits anywhere in the wizard; this class of bug has recurred."),
 ("14.6","P2","Check accessibility gating",
  "`eslint-plugin-jsx-a11y` in `eslint.config.js`; `npm run lint:screens`",
  "A11y rules are errors rather than warnings on the screens, and keyboard navigation works on the critical path."),
 ("14.7","P3","Assess the CSS and design-token migration",
  "`docs/css-roadmap.md`; `client/src/styles/`",
  "The tokens-to-pilot plan has an owner and a next milestone, or is formally paused."),
]) 

# ───────────────────────────────────────────────────────────────────────────
S("15", "Documentation And Handover",
  "The last mile of enterprise readiness: can a new engineer, or a customer's auditor, get what they need without you?",
[
 ("15.1","P2","Verify the runbooks are current and rehearsed",
  "`docs/runbooks/` (disaster-recovery, incident-response, sso-mfa-break-glass, validate-not-valid-fks)",
  "Each runbook names an owner, a last-rehearsed date, and works when followed literally."),
 ("15.2","P2","Check the deployment guide reproduces a working environment",
  "`DEPLOYMENT.md` (32 KB), `README.md`, `CONTRIBUTING.md`",
  "A new engineer reaches a running local stack, and an operator a running production stack, from the documents alone."),
 ("15.3","P2","Confirm the API is documented for its consumers",
  "`server/src/routes/`; any OpenAPI or schema export",
  "There is a generated or maintained API reference, or a written decision that the client is the only consumer."),
 ("15.4","P3","Record architecture decisions",
  "`docs/architecture.md`; the decisions in items 5.3, 5.9, 6.2 and 10.1",
  "Each significant trade-off has a short written record: context, decision, consequences."),
 ("15.5","P2","Close the loop on this review",
  "This checklist; `docs/CODEBASE_AUDIT_2026-08.md`",
  "Every P1 is closed or has a dated, signed-off acceptance; the review is re-run on a stated cadence."),
]) 

# ── Appendix A: open findings carried forward ──────────────────────────────
APPENDIX = [
 ("A1","Critical","Passwordless login is enabled on the production service",
  "`render.yaml` sets `ALLOW_NAME_AUTH: \"true\"` on the `NODE_ENV: production` service. `POST /api/auth/name-login` "
  "authenticates by display name alone and mints a full session with that user's real role. Unlike `ALLOW_DEMO_AUTH`, "
  "there is no production fence in `config/env.js` or `startup/productionPosture.js`. Chained with A2, two unauthenticated "
  "requests reach a Chief Underwriter session. Verify first, in this order: turn the flag off, add the boot fence, close A2.",
  "1.2, 1.5"),
 ("A2","High","The user directory is readable without authentication",
  "`GET /auth/users` is in the `PUBLIC_AUTH` set in `server/src/routes/auth.js`. Unauthenticated it still returns "
  "`user_id`, `username`, `display_name`, `role_name` and `role_code` for every active user — an org roster with privilege "
  "labels, useful for password spraying and phishing, and the enumeration half of A1.",
  "1.5"),
 ("A3","High","A production migration installs a shared, published password",
  "`server/src/db/migrations/132_saudi_re_demo_personas.sql` runs unconditionally via `preDeployCommand`. It sets five "
  "accounts — including one at hierarchy level 2 with approval authority — to a real scrypt hash whose plaintext is in the "
  "file header, and clears `must_change_password`. Check whether it has been applied to production, then rotate.",
  "1.8"),
 ("A4","High","Document uploads fail as production is configured",
  "No Cloudinary variables and no `ALLOW_LOCAL_UPLOADS` in `render.yaml`, so `assertLocalStorageAllowed()` in "
  "`lib/uploadStorage.js` throws `503 STORAGE_NOT_DURABLE` on every upload. The fail-closed design is correct; the manifest "
  "does not satisfy it. `checkProductionPosture()` already logs this at error level at boot.",
  "4.6"),
 ("A5","Medium","Raw error messages reach clients on 500 in production",
  "`server/src/middleware/errorHandler.js:47` returns `err.message` for any unmapped error. Stacks are correctly withheld, "
  "but driver messages can carry schema names, paths and connection detail. Return a generic message plus the request ID.",
  "4.7"),
 ("A6","Medium","Database TLS is documented but not enforced",
  "`server/src/db/pool.js` passes the connection string with no `ssl` option, so transport security depends entirely on "
  "`?sslmode=require` being present in `DATABASE_URL`. Nothing verifies it at boot.",
  "4.14"),
 ("A7","Medium","Rate limits are per-process with no shared store",
  "`REDIS_URL` is unset in `render.yaml`. Correct at one instance, but the ceiling multiplies by N the moment the service "
  "scales out or moves to PM2 cluster mode — most dangerous on the login limiter. Provision Redis before any scale-out.",
  "1.10, 10.4"),
 ("A8","Medium","No log-level control",
  "`server/src/lib/logger.js` has no `LOG_LEVEL` threshold, so `logger.debug` always writes. Impact is latent today, but "
  "there is no way to raise verbosity during an incident or suppress it under cost pressure.",
  "9.2"),
 ("A9","Low","Pricing authority originates in the browser",
  "The client derives `total_price`; `lib/pricingVerifier.js` re-derives server-side and, with `PRICING_STRICT=1`, rejects "
  "drift with 422. That is a genuine mitigation, but the authoritative financial calculation still starts in a tamperable "
  "client. Treat as a roadmap decision, not a defect.",
  "5.3"),
 ("A10","Low","Forward-only migrations with no stated rollback policy",
  "140 migrations, no `down` scripts. Recovery from a bad migration is restore-from-backup, which is what the DR runbook "
  "assumes. Reasonable — but it should be written down as policy.",
  "6.2"),
 ("A11","Low","Single instance, no redundancy",
  "`plan: starter` with no `numInstances`. Any deploy, crash or host event is full downtime. Defensible against the stated "
  "`RTO <= 4h`, but it should be an explicit, signed-off acceptance rather than an omission.",
  "10.1"),
 ("A12","Low","Client test coverage is thin where pricing lives",
  "Roughly 52% statements / 43% branches across ~80k lines of client code — the half where pricing is computed. Server "
  "coverage is materially better. The ratchet policy is sound; the client floor needs raising over time.",
  "12.1"),
]
